const GET_ITEM_LIST = "GET_ITEM_LIST";
const ADD_QUANTITY = "ADD_QUANTITY";
const REMOVE_QUANTITY = "REMOVE_QUANTITY";
const GET_SIZE_LIST = "GET_SIZE_LIST";
const CALCULATE_TOTAL = "CALCULATE_TOTAL";

export default {
  GET_ITEM_LIST,
  ADD_QUANTITY,
  REMOVE_QUANTITY,
  GET_SIZE_LIST,
  CALCULATE_TOTAL
};
